boxes:
- dimensions: [0.1, 0.1, 0.1]
  frame_id: base
  name: jane_eyre_dvd
  orientation: [0, 0, 0, 1]
  position: [0, 0, 0]
- dimensions: [0.1, 0.1, 0.1]
  frame_id: base
  name: clorox_utility_brush
  orientation: [0.0, 0.0, 0.0, 1.0]
  position: [0.0, 0.0, 0.0]
- dimensions: [0.1, 0.1, 0.1]
  frame_id: base
  name: crayola_24_ct
  orientation: [0.0, 0.0, 0.0, 1.0]
  position: [1.0136311054229736, 0.0, 0.6768686771392822]
