#!/usr/bin/env python

import jsk_apc2016_common


object_data = jsk_apc2016_common.get_object_data()

print(' 0: background')
for i, row in enumerate(object_data):
    label_value = i + 1
    label_name = row['name']
    print('{:2}: {}'.format(label_value, label_name))
